#!/usr/bin/env bash
set -x
set -e

"$(dirname "$0")/postgres-init-dev-db" yakkl_test "$("$(dirname "$0")/../../scripts/get-django-setting" LOCAL_DATABASE_PASSWORD)" yakkl_test yakkl,public migration_status_test
