# YAKKL Wallet v2 Configuration
version: "2.0.0"
product_name: "YAKKL Wallet V2"
product_short: "YAKKL V2"

# Build configuration
build:
  hooks_client: "./src/hooks.client.v2.ts"
  app_html: "./src/app.v2.html"
  
# Extension paths
paths:
  extension_root: "./src/lib/ext/chrome"
  background_script: "./src/lib/ext/chrome/background/index.ts"
  content_script: "./src/lib/ext/chrome/content.ts"
  inpage_script: "./src/lib/ext/chrome/inpage.ts"
  manifest_template: "./src/lib/ext/chrome/manifest.json.mustache"
  initial_route: "/"
  
# UI configuration
ui:
  popup_width: 428
  popup_height: 926
  show_testnet_default: true
  theme_default: "dark"
  
# Feature flags
features:
  preview_mode: true
  legacy_storage: false
  ai_assistant: true
  advanced_analytics: true
  secure_recovery: true
  
# Environment
env:
  node_env: "development"
  dev_mode: true