[program:yakkl-thumbor]
command=/home/yakkl/deployments/current/yakkl-thumbor-venv/bin/thumbor --port=9995 --conf=/home/yakkl/deployments/current/zthumbor/thumbor.conf
user=yakkl
directory=/home/yakkl/deployments/current/
autostart=true
autorestart=true
startretries=3
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/var/log/yakkl/thumbor.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3
