
// this file is generated — do not edit it


/// <reference types="@sveltejs/kit" />

/**
 * Environment variables [loaded by Vite](https://vitejs.dev/guide/env-and-mode.html#env-files) from `.env` files and `process.env`. Like [`$env/dynamic/private`](https://svelte.dev/docs/kit/$env-dynamic-private), this module cannot be imported into client-side code. This module only includes variables that _do not_ begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) _and do_ start with [`config.kit.env.privatePrefix`](https://svelte.dev/docs/kit/configuration#env) (if configured).
 * 
 * _Unlike_ [`$env/dynamic/private`](https://svelte.dev/docs/kit/$env-dynamic-private), the values exported from this module are statically injected into your bundle at build time, enabling optimisations like dead code elimination.
 * 
 * ```ts
 * import { API_KEY } from '$env/static/private';
 * ```
 * 
 * Note that all environment variables referenced in your code should be declared (for example in an `.env` file), even if they don't have a value until the app is deployed:
 * 
 * ```
 * MY_FEATURE_FLAG=""
 * ```
 * 
 * You can override `.env` values from the command line like so:
 * 
 * ```bash
 * MY_FEATURE_FLAG="enabled" npm run dev
 * ```
 */
declare module '$env/static/private' {
	export const VITE_YAKKL_API_KEY: string;
	export const YAKKL_TYPE: string;
	export const DEV_MODE: string;
	export const VITE_YAKKL_TYPE: string;
	export const VITE_DEV_MODE: string;
	export const VITE_VERSION: string;
	export const VITE_IS_SIDEPANEL: string;
	export const VITE_IS_POPUP: string;
	export const VITE_ALCHEMY_API_KEY_ETHEREUM: string;
	export const VITE_ALCHEMY_API_KEY_PROD: string;
	export const ALCHEMY_API_KEY_PROD: string;
	export const VITE_ALCHEMY_API_KEY_POLYGON: string;
	export const VITE_ALCHEMY_API_KEY_POLYGON_PROD: string;
	export const VITE_ALCHEMY_API_KEY_SOLANA: string;
	export const VITE_ALCHEMY_API_KEY_SOLANA_PROD: string;
	export const VITE_ALCHEMY_API_KEY_ARBITRUM: string;
	export const VITE_ALCHEMY_API_KEY_ARBITRUM_PROD: string;
	export const VITE_ETHERSCAN_API_KEY: string;
	export const VITE_INFURA_API_KEY_WEB3D: string;
	export const VITE_INFURA_API_KEY_WEB3P: string;
	export const VITE_CHAINSTACK_API_KEY_DEV: string;
	export const VITE_CHAINSTACK_API_KEY_PROD: string;
	export const VITE_COINGECKO_API_KEY: string;
	export const VITE_ALLTHATNODE_API_KEY: string;
	export const VITE_PEXEL_API_KEY: string;
	export const VITE_GOOGLE_CLIENT_ID: string;
	export const VITE_CHROME_DEV_ID: string;
	export const VITE_CHROME_PROD_ID: string;
	export const VITE_ETHERSCAN_ENDPOINT_MAINNET: string;
	export const VITE_ETHERSCAN_ENDPOINT_GOERLI: string;
	export const VITE_ETHERSCAN_ENDPOINT_SEPOLIA: string;
	export const VITE_GAS_BLOCKNATIVE_ENDPOINT: string;
	export const VITE_GAS_ETHERSCAN_ENDPOINT: string;
	export const VITE_GAS_ETHGASSTATION_ENDPOINT: string;
	export const VITE_GPT_API_KEY: string;
	export const VITE_GPT_API_KEY_OLD: string;
	export const VITE_GPT_API_KEY_BACKUP: string;
	export const VITE_GPT_API_KEY_BACKEND_URL: string;
	export const VITE_GPT_API_KEY_BACKEND: string;
	export const VITE_QUICKNODE_ENDPOINT_GOERLI: string;
	export const VITE_QUICKNODE_ENDPOINT_SEPOLIA: string;
	export const VITE_QUICKNODE_ENDPOINT_MAINNET: string;
	export const VITE_COINBASE_API_KEY: string;
	export const VITE_ANKR_API_KEY: string;
	export const VITE_ETHERSCAN_ONFINALITY: string;
	export const VITE_GETBLOCK_API_KEY_DEV: string;
	export const VITE_SENTRY_DNS: string;
	export const VITE_POSTHOG_API_KEY: string;
	export const VITE_POSTHOG_API_KEY_ID: string;
	export const VITE_POSTHOG_API_HOST: string;
	export const VITE_LOCAL_MAC_EXTDIR: string;
	export const VITE_WALLET_CONNECT_WEB3CONNECT: string;
	export const VITE_WALLET_CONNECT_PROD: string;
	export const VITE_1INCH_API_KEY: string;
	export const VITE_OLD_GPT_API_KEY: string;
	export const VITE_ANTHROPIC_KEY_DEV: string;
	export const VITE_FEE_RECIPIENT: string;
	export const VITE_MESSARIO_API_KEY: string;
	export const VITE_GROK_API_KEY: string;
	export const VITE_TRADING_VIEW_LINK: string;
	export const VITE_MORALIS_API_KEY: string;
	export const VITE_TAVILY_API_KEY: string;
	export const VITE_CHATGPT_CRYPTO_GRAMPS: string;
	export const VITE_SERPER_API_KEY: string;
	export const VITE_PERPLEXITY_API_KEY: string;
	export const VITE_CLOUDFLARE_AI_KEY: string;
	export const VITE_CLOUDFLARE_ACCOUNT_ID: string;
	export const VITE_CLOUDFLARE_GATEWAY_ID: string;
	export const VITE_CIRCLE_API_KEY: string;
	export const VITE_CHROME_AI_TOKEN_PROD: string;
	export const VITE_CHROME_AI_TOKEN_DEV: string;
	export const VITE_COINDESK_API_KEY: string;
	export const VITE_COINDESK_TEST_API_KEY: string;
	export const tmp_getMemoizedKey: string;
	export const NVM_INC: string;
	export const npm_package_scripts_build_constants: string;
	export const npm_package_devDependencies__tailwindcss_typography: string;
	export const COREPACK_ROOT: string;
	export const npm_package_devDependencies__eslint_compat: string;
	export const npm_package_devDependencies__tanstack_table_core: string;
	export const npm_package_devDependencies__uniswap_v3_periphery: string;
	export const npm_package_devDependencies_prettier: string;
	export const npm_package_devDependencies_tailwindcss_animate: string;
	export const npm_package_devDependencies_sveltekit_adapter_chrome_extension: string;
	export const CLAUDE_CODE_ENTRYPOINT: string;
	export const TERM_PROGRAM: string;
	export const npm_package_devDependencies_eslint_plugin_svelte: string;
	export const npm_package_devDependencies_idb: string;
	export const npm_package_devDependencies_typescript_eslint: string;
	export const NODE: string;
	export const npm_package_scripts_build_clean: string;
	export const npm_package_dependencies__walletconnect_web3wallet: string;
	export const npm_package_dependencies_cheerio: string;
	export const npm_package_dependencies_is_stream: string;
	export const npm_package_dependencies_process: string;
	export const INIT_CWD: string;
	export const NVM_CD_FLAGS: string;
	export const npm_package_devDependencies_prettier_plugin_svelte: string;
	export const npm_package_devDependencies_terser_webpack_plugin: string;
	export const npm_package_devDependencies_typescript: string;
	export const SHELL: string;
	export const TERM: string;
	export const npm_package_devDependencies__types_webextension_polyfill: string;
	export const npm_package_devDependencies_jest: string;
	export const npm_package_devDependencies_vite: string;
	export const TMPDIR: string;
	export const npm_package_version_sub: string;
	export const npm_package_scripts_build_swaplist: string;
	export const npm_package_devDependencies_clsx: string;
	export const npm_package_dependencies_url: string;
	export const npm_package_scripts_lint: string;
	export const npm_package_devDependencies__babel_preset_typescript: string;
	export const npm_package_devDependencies_svelte_forms_lib: string;
	export const TERM_PROGRAM_VERSION: string;
	export const npm_package_devDependencies_flowbite: string;
	export const npm_package_devDependencies_mustache: string;
	export const npm_package_devDependencies_tailwindcss_dotted_background: string;
	export const npm_package_dependencies_assert: string;
	export const npm_package_dependencies_svelte_confetti: string;
	export const MallocNanoZone: string;
	export const ORIGINAL_XDG_CURRENT_DESKTOP: string;
	export const CURSOR_TRACE_ID: string;
	export const ZDOTDIR: string;
	export const npm_package_devDependencies__rollup_plugin_replace: string;
	export const npm_package_devDependencies__types_ledgerhq__hw_transport: string;
	export const npm_package_dependencies_uuid: string;
	export const npm_package_devDependencies_fs: string;
	export const npm_package_devDependencies_install: string;
	export const npm_package_devDependencies_zxcvbn: string;
	export const npm_package_config_environments_prod_DEV_MODE: string;
	export const npm_package_devDependencies__sveltejs_kit: string;
	export const npm_package_devDependencies_net_browserify: string;
	export const npm_package_devDependencies_rollup_plugin_node_polyfills: string;
	export const npm_package_dependencies__ledgerhq_hw_app_eth: string;
	export const npm_config_registry: string;
	export const ZSH: string;
	export const ENABLE_IDE_INTEGRATION: string;
	export const npm_package_devDependencies_npm: string;
	export const npm_package_devDependencies_vite_plugin_static_copy: string;
	export const GIT_EDITOR: string;
	export const npm_package_scripts_dev_chrome: string;
	export const npm_package_devDependencies_alchemy_sdk: string;
	export const npm_package_devDependencies_globals: string;
	export const USER: string;
	export const ZSH_TMUX_TERM: string;
	export const NVM_DIR: string;
	export const npm_package_devDependencies_phosphor_svelte: string;
	export const npm_package_devDependencies_tailwind_variants: string;
	export const npm_package_devDependencies_webpack: string;
	export const npm_config_recursive: string;
	export const LS_COLORS: string;
	export const npm_package_scripts_check_watch: string;
	export const npm_package_devDependencies_dotenv: string;
	export const npm_package_devDependencies_vite_plugin_iso_import: string;
	export const npm_package_devDependencies_webpack_cli: string;
	export const npm_package_dependencies__ethersproject_properties: string;
	export const COMMAND_MODE: string;
	export const npm_package_scripts_dev_v2_chrome: string;
	export const npm_package_devDependencies_zod: string;
	export const PNPM_SCRIPT_SRC_DIR: string;
	export const npm_package_devDependencies__sveltejs_adapter_static: string;
	export const npm_package_devDependencies_detect_browser: string;
	export const _ZSH_TMUX_FIXED_CONFIG: string;
	export const npm_package_devDependencies__babel_core: string;
	export const npm_package_devDependencies_babel_jest: string;
	export const SSH_AUTH_SOCK: string;
	export const CLAUDE_CODE_SSE_PORT: string;
	export const npm_package_config_environments_dev_DEV_MODE: string;
	export const npm_package_devDependencies_babel_loader: string;
	export const __CF_USER_TEXT_ENCODING: string;
	export const npm_package_devDependencies__types_jest: string;
	export const npm_package_devDependencies_eslint: string;
	export const npm_package_devDependencies_postcss: string;
	export const npm_package_devDependencies_svelte_sonner: string;
	export const npm_package_dependencies_buffer: string;
	export const npm_package_devDependencies__typescript_eslint_eslint_plugin: string;
	export const npm_package_devDependencies_tslib: string;
	export const npm_package_dependencies_node_fetch: string;
	export const npm_execpath: string;
	export const PAGER: string;
	export const npm_package_devDependencies__uniswap_universal_router_sdk: string;
	export const npm_package_devDependencies_svelte: string;
	export const npm_package_dependencies__rollup_plugin_commonjs: string;
	export const npm_package_dependencies_https_browserify: string;
	export const PYDEVD_DISABLE_FILE_VALIDATION: string;
	export const npm_package_scripts_build_env_dev: string;
	export const npm_package_devDependencies_formsnap: string;
	export const npm_package_devDependencies_vaul_svelte: string;
	export const LSCOLORS: string;
	export const npm_package_devDependencies_copy_webpack_plugin: string;
	export const npm_config_frozen_lockfile: string;
	export const npm_package_devDependencies__typescript_eslint_parser: string;
	export const npm_package_devDependencies_stream: string;
	export const npm_package_devDependencies_sveltekit_superforms: string;
	export const PATH: string;
	export const npm_package_scripts_build_tsc: string;
	export const npm_package_devDependencies_bits_ui: string;
	export const npm_package_scripts_check_public: string;
	export const npm_package_scripts_build_env: string;
	export const npm_package_scripts_chrome_store_zip: string;
	export const npm_package_devDependencies_ethers_v6: string;
	export const npm_package_devDependencies_openai: string;
	export const npm_package_devDependencies_rollup: string;
	export const npm_package_devDependencies__neoconfetti_svelte: string;
	export const npm_package_devDependencies__tailwindcss_aspect_ratio: string;
	export const npm_package_dependencies_esbuild: string;
	export const npm_config_engine_strict: string;
	export const COREPACK_ENABLE_DOWNLOAD_PROMPT: string;
	export const __CFBundleIdentifier: string;
	export const USER_ZDOTDIR: string;
	export const npm_package_config_environments_dev_YAKKL_TYPE: string;
	export const npm_package_scripts_dev_chrome_proprv: string;
	export const npm_package_devDependencies_ts_jest: string;
	export const npm_package_dependencies_stream_http: string;
	export const PWD: string;
	export const npm_package_devDependencies__unovis_svelte: string;
	export const npm_package_devDependencies_tailwindcss: string;
	export const npm_package_devDependencies_terser: string;
	export const npm_command: string;
	export const npm_package_scripts_build_v2_chrome: string;
	export const npm_package_scripts_build_debug: string;
	export const npm_package_scripts_preview: string;
	export const npm_package_devDependencies__types_lodash: string;
	export const npm_package_devDependencies_lucide_svelte: string;
	export const npm_package_dependencies__yakkl_core: string;
	export const OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: string;
	export const npm_package_devDependencies_flowbite_svelte_icons: string;
	export const npm_package_dependencies__uniswap_v3_core: string;
	export const npm_lifecycle_event: string;
	export const LANG: string;
	export const npm_package_name: string;
	export const npm_package_types: string;
	export const npm_package_devDependencies__sveltejs_vite_plugin_svelte: string;
	export const npm_package_devDependencies_crypto_browserify: string;
	export const CLOUDSDK_HOME: string;
	export const BUNDLED_DEBUGPY_PATH: string;
	export const npm_package_devDependencies__babel_preset_env: string;
	export const npm_package_devDependencies__tailwindcss_container_queries: string;
	export const npm_package_dependencies__ethersproject_web: string;
	export const NODE_PATH: string;
	export const npm_package_devDependencies__babel_cli: string;
	export const XPC_FLAGS: string;
	export const VSCODE_GIT_ASKPASS_EXTRA_ARGS: string;
	export const npm_package_scripts_dev2_core: string;
	export const npm_package_scripts_build_v1_chrome: string;
	export const npm_package_devDependencies__uniswap_permit2_sdk: string;
	export const npm_package_devDependencies_ethers: string;
	export const npm_package_devDependencies_paneforge: string;
	export const npm_package_devDependencies_ts_loader: string;
	export const npm_package_devDependencies_vitest: string;
	export const npm_package_config_environments_prod_YAKKL_TYPE: string;
	export const npm_package_devDependencies__tailwindcss_forms: string;
	export const npm_package_devDependencies_flowbite_svelte: string;
	export const npm_package_devDependencies_mode_watcher: string;
	export const npm_package_devDependencies_vm_browserify: string;
	export const npm_package_dependencies_os_browserify: string;
	export const npm_package_config_instructions: string;
	export const npm_package_scripts_build_config_v1: string;
	export const npm_package_devDependencies__types_lodash_es: string;
	export const npm_package_devDependencies_dexie: string;
	export const npm_package_devDependencies_path: string;
	export const npm_package_devDependencies_tailwind_merge: string;
	export const npm_package_engines_node: string;
	export const npm_package_scripts_build_config_v2: string;
	export const npm_package_devDependencies_eslint_config_prettier: string;
	export const npm_package_devDependencies_lodash_es: string;
	export const npm_config_node_gyp: string;
	export const XPC_SERVICE_NAME: string;
	export const npm_package_version: string;
	export const npm_package_scripts_prepare_original: string;
	export const npm_package_devDependencies__sushiswap_sdk: string;
	export const npm_package_devDependencies__sveltejs_adapter_auto: string;
	export const npm_package_dependencies__ledgerhq_hw_transport_webusb: string;
	export const VSCODE_DEBUGPY_ADAPTER_ENDPOINTS: string;
	export const VSCODE_INJECTION: string;
	export const npm_package_devDependencies__types_readable_stream: string;
	export const npm_package_devDependencies_autoprefixer: string;
	export const npm_package_devDependencies_daisyui: string;
	export const npm_package_devDependencies_svelte_check: string;
	export const npm_package_dependencies_svelte_chartjs: string;
	export const HOME: string;
	export const SHLVL: string;
	export const npm_package_config_YAKKL_TYPE: string;
	export const npm_package_scripts_build_chrome_proprv: string;
	export const npm_package_devDependencies__types_bn_js: string;
	export const npm_package_devDependencies__uniswap_v3_sdk: string;
	export const npm_package_devDependencies_easyqrcodejs: string;
	export const npm_package_devDependencies_webextension_polyfill: string;
	export const npm_package_type: string;
	export const VSCODE_GIT_ASKPASS_MAIN: string;
	export const npm_package_scripts_dev_v1_chrome: string;
	export const npm_package_scripts_test: string;
	export const npm_package_devDependencies_clipboard: string;
	export const npm_package_dependencies__ledgerhq_hw_transport_webhid: string;
	export const npm_package_devDependencies_lodash: string;
	export const npm_package_devDependencies_node_polyfill_webpack_plugin: string;
	export const npm_package_scripts_build_env_prod: string;
	export const npm_package_devDependencies__internationalized_date: string;
	export const npm_package_dependencies__rollup_plugin_node_resolve: string;
	export const LOGNAME: string;
	export const LESS: string;
	export const npm_package_scripts_build_chrome: string;
	export const npm_package_scripts_firefox_store_zip: string;
	export const npm_package_scripts_format: string;
	export const npm_package_devDependencies_embla_carousel_svelte: string;
	export const npm_package_devDependencies_ethereum_blockies_base64: string;
	export const npm_lifecycle_script: string;
	export const VSCODE_GIT_IPC_HANDLE: string;
	export const npm_package_devDependencies_prettier_plugin_tailwindcss: string;
	export const COREPACK_ENABLE_AUTO_PIN: string;
	export const npm_package_scripts_package: string;
	export const npm_package_devDependencies_vite_plugin_node_polyfills: string;
	export const NVM_BIN: string;
	export const npm_package_devDependencies__types_chrome: string;
	export const npm_package_devDependencies__types_mustache: string;
	export const npm_package_devDependencies_readable_stream: string;
	export const npm_package_scripts_dev2_chrome: string;
	export const npm_package_devDependencies__types_uuid: string;
	export const npm_package_devDependencies__types_zxcvbn: string;
	export const npm_package_devDependencies_dts_cli: string;
	export const npm_config_user_agent: string;
	export const GIT_ASKPASS: string;
	export const VSCODE_GIT_ASKPASS_NODE: string;
	export const npm_package_devDependencies__playwright_test: string;
	export const npm_package_devDependencies__types_node: string;
	export const npm_package_devDependencies_stream_browserify: string;
	export const npm_package_devDependencies_axios: string;
	export const npm_package_devDependencies_dotenv_webpack: string;
	export const npm_package_devDependencies_path_browserify: string;
	export const npm_package_devDependencies_svelte_radix: string;
	export const npm_package_scripts_prepare: string;
	export const npm_package_devDependencies__uniswap_sdk_core: string;
	export const CLAUDECODE: string;
	export const npm_package_scripts_check: string;
	export const npm_package_devDependencies_yup: string;
	export const COLORTERM: string;
	export const npm_package_devDependencies__uniswap_router_sdk: string;
	export const npm_node_execpath: string;
	export const NODE_ENV: string;
}

/**
 * Similar to [`$env/static/private`](https://svelte.dev/docs/kit/$env-static-private), except that it only includes environment variables that begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) (which defaults to `PUBLIC_`), and can therefore safely be exposed to client-side code.
 * 
 * Values are replaced statically at build time.
 * 
 * ```ts
 * import { PUBLIC_BASE_URL } from '$env/static/public';
 * ```
 */
declare module '$env/static/public' {
	
}

/**
 * This module provides access to runtime environment variables, as defined by the platform you're running on. For example if you're using [`adapter-node`](https://github.com/sveltejs/kit/tree/main/packages/adapter-node) (or running [`vite preview`](https://svelte.dev/docs/kit/cli)), this is equivalent to `process.env`. This module only includes variables that _do not_ begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) _and do_ start with [`config.kit.env.privatePrefix`](https://svelte.dev/docs/kit/configuration#env) (if configured).
 * 
 * This module cannot be imported into client-side code.
 * 
 * Dynamic environment variables cannot be used during prerendering.
 * 
 * ```ts
 * import { env } from '$env/dynamic/private';
 * console.log(env.DEPLOYMENT_SPECIFIC_VARIABLE);
 * ```
 * 
 * > In `dev`, `$env/dynamic` always includes environment variables from `.env`. In `prod`, this behavior will depend on your adapter.
 */
declare module '$env/dynamic/private' {
	export const env: {
		VITE_YAKKL_API_KEY: string;
		YAKKL_TYPE: string;
		DEV_MODE: string;
		VITE_YAKKL_TYPE: string;
		VITE_DEV_MODE: string;
		VITE_VERSION: string;
		VITE_IS_SIDEPANEL: string;
		VITE_IS_POPUP: string;
		VITE_ALCHEMY_API_KEY_ETHEREUM: string;
		VITE_ALCHEMY_API_KEY_PROD: string;
		ALCHEMY_API_KEY_PROD: string;
		VITE_ALCHEMY_API_KEY_POLYGON: string;
		VITE_ALCHEMY_API_KEY_POLYGON_PROD: string;
		VITE_ALCHEMY_API_KEY_SOLANA: string;
		VITE_ALCHEMY_API_KEY_SOLANA_PROD: string;
		VITE_ALCHEMY_API_KEY_ARBITRUM: string;
		VITE_ALCHEMY_API_KEY_ARBITRUM_PROD: string;
		VITE_ETHERSCAN_API_KEY: string;
		VITE_INFURA_API_KEY_WEB3D: string;
		VITE_INFURA_API_KEY_WEB3P: string;
		VITE_CHAINSTACK_API_KEY_DEV: string;
		VITE_CHAINSTACK_API_KEY_PROD: string;
		VITE_COINGECKO_API_KEY: string;
		VITE_ALLTHATNODE_API_KEY: string;
		VITE_PEXEL_API_KEY: string;
		VITE_GOOGLE_CLIENT_ID: string;
		VITE_CHROME_DEV_ID: string;
		VITE_CHROME_PROD_ID: string;
		VITE_ETHERSCAN_ENDPOINT_MAINNET: string;
		VITE_ETHERSCAN_ENDPOINT_GOERLI: string;
		VITE_ETHERSCAN_ENDPOINT_SEPOLIA: string;
		VITE_GAS_BLOCKNATIVE_ENDPOINT: string;
		VITE_GAS_ETHERSCAN_ENDPOINT: string;
		VITE_GAS_ETHGASSTATION_ENDPOINT: string;
		VITE_GPT_API_KEY: string;
		VITE_GPT_API_KEY_OLD: string;
		VITE_GPT_API_KEY_BACKUP: string;
		VITE_GPT_API_KEY_BACKEND_URL: string;
		VITE_GPT_API_KEY_BACKEND: string;
		VITE_QUICKNODE_ENDPOINT_GOERLI: string;
		VITE_QUICKNODE_ENDPOINT_SEPOLIA: string;
		VITE_QUICKNODE_ENDPOINT_MAINNET: string;
		VITE_COINBASE_API_KEY: string;
		VITE_ANKR_API_KEY: string;
		VITE_ETHERSCAN_ONFINALITY: string;
		VITE_GETBLOCK_API_KEY_DEV: string;
		VITE_SENTRY_DNS: string;
		VITE_POSTHOG_API_KEY: string;
		VITE_POSTHOG_API_KEY_ID: string;
		VITE_POSTHOG_API_HOST: string;
		VITE_LOCAL_MAC_EXTDIR: string;
		VITE_WALLET_CONNECT_WEB3CONNECT: string;
		VITE_WALLET_CONNECT_PROD: string;
		VITE_1INCH_API_KEY: string;
		VITE_OLD_GPT_API_KEY: string;
		VITE_ANTHROPIC_KEY_DEV: string;
		VITE_FEE_RECIPIENT: string;
		VITE_MESSARIO_API_KEY: string;
		VITE_GROK_API_KEY: string;
		VITE_TRADING_VIEW_LINK: string;
		VITE_MORALIS_API_KEY: string;
		VITE_TAVILY_API_KEY: string;
		VITE_CHATGPT_CRYPTO_GRAMPS: string;
		VITE_SERPER_API_KEY: string;
		VITE_PERPLEXITY_API_KEY: string;
		VITE_CLOUDFLARE_AI_KEY: string;
		VITE_CLOUDFLARE_ACCOUNT_ID: string;
		VITE_CLOUDFLARE_GATEWAY_ID: string;
		VITE_CIRCLE_API_KEY: string;
		VITE_CHROME_AI_TOKEN_PROD: string;
		VITE_CHROME_AI_TOKEN_DEV: string;
		VITE_COINDESK_API_KEY: string;
		VITE_COINDESK_TEST_API_KEY: string;
		tmp_getMemoizedKey: string;
		NVM_INC: string;
		npm_package_scripts_build_constants: string;
		npm_package_devDependencies__tailwindcss_typography: string;
		COREPACK_ROOT: string;
		npm_package_devDependencies__eslint_compat: string;
		npm_package_devDependencies__tanstack_table_core: string;
		npm_package_devDependencies__uniswap_v3_periphery: string;
		npm_package_devDependencies_prettier: string;
		npm_package_devDependencies_tailwindcss_animate: string;
		npm_package_devDependencies_sveltekit_adapter_chrome_extension: string;
		CLAUDE_CODE_ENTRYPOINT: string;
		TERM_PROGRAM: string;
		npm_package_devDependencies_eslint_plugin_svelte: string;
		npm_package_devDependencies_idb: string;
		npm_package_devDependencies_typescript_eslint: string;
		NODE: string;
		npm_package_scripts_build_clean: string;
		npm_package_dependencies__walletconnect_web3wallet: string;
		npm_package_dependencies_cheerio: string;
		npm_package_dependencies_is_stream: string;
		npm_package_dependencies_process: string;
		INIT_CWD: string;
		NVM_CD_FLAGS: string;
		npm_package_devDependencies_prettier_plugin_svelte: string;
		npm_package_devDependencies_terser_webpack_plugin: string;
		npm_package_devDependencies_typescript: string;
		SHELL: string;
		TERM: string;
		npm_package_devDependencies__types_webextension_polyfill: string;
		npm_package_devDependencies_jest: string;
		npm_package_devDependencies_vite: string;
		TMPDIR: string;
		npm_package_version_sub: string;
		npm_package_scripts_build_swaplist: string;
		npm_package_devDependencies_clsx: string;
		npm_package_dependencies_url: string;
		npm_package_scripts_lint: string;
		npm_package_devDependencies__babel_preset_typescript: string;
		npm_package_devDependencies_svelte_forms_lib: string;
		TERM_PROGRAM_VERSION: string;
		npm_package_devDependencies_flowbite: string;
		npm_package_devDependencies_mustache: string;
		npm_package_devDependencies_tailwindcss_dotted_background: string;
		npm_package_dependencies_assert: string;
		npm_package_dependencies_svelte_confetti: string;
		MallocNanoZone: string;
		ORIGINAL_XDG_CURRENT_DESKTOP: string;
		CURSOR_TRACE_ID: string;
		ZDOTDIR: string;
		npm_package_devDependencies__rollup_plugin_replace: string;
		npm_package_devDependencies__types_ledgerhq__hw_transport: string;
		npm_package_dependencies_uuid: string;
		npm_package_devDependencies_fs: string;
		npm_package_devDependencies_install: string;
		npm_package_devDependencies_zxcvbn: string;
		npm_package_config_environments_prod_DEV_MODE: string;
		npm_package_devDependencies__sveltejs_kit: string;
		npm_package_devDependencies_net_browserify: string;
		npm_package_devDependencies_rollup_plugin_node_polyfills: string;
		npm_package_dependencies__ledgerhq_hw_app_eth: string;
		npm_config_registry: string;
		ZSH: string;
		ENABLE_IDE_INTEGRATION: string;
		npm_package_devDependencies_npm: string;
		npm_package_devDependencies_vite_plugin_static_copy: string;
		GIT_EDITOR: string;
		npm_package_scripts_dev_chrome: string;
		npm_package_devDependencies_alchemy_sdk: string;
		npm_package_devDependencies_globals: string;
		USER: string;
		ZSH_TMUX_TERM: string;
		NVM_DIR: string;
		npm_package_devDependencies_phosphor_svelte: string;
		npm_package_devDependencies_tailwind_variants: string;
		npm_package_devDependencies_webpack: string;
		npm_config_recursive: string;
		LS_COLORS: string;
		npm_package_scripts_check_watch: string;
		npm_package_devDependencies_dotenv: string;
		npm_package_devDependencies_vite_plugin_iso_import: string;
		npm_package_devDependencies_webpack_cli: string;
		npm_package_dependencies__ethersproject_properties: string;
		COMMAND_MODE: string;
		npm_package_scripts_dev_v2_chrome: string;
		npm_package_devDependencies_zod: string;
		PNPM_SCRIPT_SRC_DIR: string;
		npm_package_devDependencies__sveltejs_adapter_static: string;
		npm_package_devDependencies_detect_browser: string;
		_ZSH_TMUX_FIXED_CONFIG: string;
		npm_package_devDependencies__babel_core: string;
		npm_package_devDependencies_babel_jest: string;
		SSH_AUTH_SOCK: string;
		CLAUDE_CODE_SSE_PORT: string;
		npm_package_config_environments_dev_DEV_MODE: string;
		npm_package_devDependencies_babel_loader: string;
		__CF_USER_TEXT_ENCODING: string;
		npm_package_devDependencies__types_jest: string;
		npm_package_devDependencies_eslint: string;
		npm_package_devDependencies_postcss: string;
		npm_package_devDependencies_svelte_sonner: string;
		npm_package_dependencies_buffer: string;
		npm_package_devDependencies__typescript_eslint_eslint_plugin: string;
		npm_package_devDependencies_tslib: string;
		npm_package_dependencies_node_fetch: string;
		npm_execpath: string;
		PAGER: string;
		npm_package_devDependencies__uniswap_universal_router_sdk: string;
		npm_package_devDependencies_svelte: string;
		npm_package_dependencies__rollup_plugin_commonjs: string;
		npm_package_dependencies_https_browserify: string;
		PYDEVD_DISABLE_FILE_VALIDATION: string;
		npm_package_scripts_build_env_dev: string;
		npm_package_devDependencies_formsnap: string;
		npm_package_devDependencies_vaul_svelte: string;
		LSCOLORS: string;
		npm_package_devDependencies_copy_webpack_plugin: string;
		npm_config_frozen_lockfile: string;
		npm_package_devDependencies__typescript_eslint_parser: string;
		npm_package_devDependencies_stream: string;
		npm_package_devDependencies_sveltekit_superforms: string;
		PATH: string;
		npm_package_scripts_build_tsc: string;
		npm_package_devDependencies_bits_ui: string;
		npm_package_scripts_check_public: string;
		npm_package_scripts_build_env: string;
		npm_package_scripts_chrome_store_zip: string;
		npm_package_devDependencies_ethers_v6: string;
		npm_package_devDependencies_openai: string;
		npm_package_devDependencies_rollup: string;
		npm_package_devDependencies__neoconfetti_svelte: string;
		npm_package_devDependencies__tailwindcss_aspect_ratio: string;
		npm_package_dependencies_esbuild: string;
		npm_config_engine_strict: string;
		COREPACK_ENABLE_DOWNLOAD_PROMPT: string;
		__CFBundleIdentifier: string;
		USER_ZDOTDIR: string;
		npm_package_config_environments_dev_YAKKL_TYPE: string;
		npm_package_scripts_dev_chrome_proprv: string;
		npm_package_devDependencies_ts_jest: string;
		npm_package_dependencies_stream_http: string;
		PWD: string;
		npm_package_devDependencies__unovis_svelte: string;
		npm_package_devDependencies_tailwindcss: string;
		npm_package_devDependencies_terser: string;
		npm_command: string;
		npm_package_scripts_build_v2_chrome: string;
		npm_package_scripts_build_debug: string;
		npm_package_scripts_preview: string;
		npm_package_devDependencies__types_lodash: string;
		npm_package_devDependencies_lucide_svelte: string;
		npm_package_dependencies__yakkl_core: string;
		OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: string;
		npm_package_devDependencies_flowbite_svelte_icons: string;
		npm_package_dependencies__uniswap_v3_core: string;
		npm_lifecycle_event: string;
		LANG: string;
		npm_package_name: string;
		npm_package_types: string;
		npm_package_devDependencies__sveltejs_vite_plugin_svelte: string;
		npm_package_devDependencies_crypto_browserify: string;
		CLOUDSDK_HOME: string;
		BUNDLED_DEBUGPY_PATH: string;
		npm_package_devDependencies__babel_preset_env: string;
		npm_package_devDependencies__tailwindcss_container_queries: string;
		npm_package_dependencies__ethersproject_web: string;
		NODE_PATH: string;
		npm_package_devDependencies__babel_cli: string;
		XPC_FLAGS: string;
		VSCODE_GIT_ASKPASS_EXTRA_ARGS: string;
		npm_package_scripts_dev2_core: string;
		npm_package_scripts_build_v1_chrome: string;
		npm_package_devDependencies__uniswap_permit2_sdk: string;
		npm_package_devDependencies_ethers: string;
		npm_package_devDependencies_paneforge: string;
		npm_package_devDependencies_ts_loader: string;
		npm_package_devDependencies_vitest: string;
		npm_package_config_environments_prod_YAKKL_TYPE: string;
		npm_package_devDependencies__tailwindcss_forms: string;
		npm_package_devDependencies_flowbite_svelte: string;
		npm_package_devDependencies_mode_watcher: string;
		npm_package_devDependencies_vm_browserify: string;
		npm_package_dependencies_os_browserify: string;
		npm_package_config_instructions: string;
		npm_package_scripts_build_config_v1: string;
		npm_package_devDependencies__types_lodash_es: string;
		npm_package_devDependencies_dexie: string;
		npm_package_devDependencies_path: string;
		npm_package_devDependencies_tailwind_merge: string;
		npm_package_engines_node: string;
		npm_package_scripts_build_config_v2: string;
		npm_package_devDependencies_eslint_config_prettier: string;
		npm_package_devDependencies_lodash_es: string;
		npm_config_node_gyp: string;
		XPC_SERVICE_NAME: string;
		npm_package_version: string;
		npm_package_scripts_prepare_original: string;
		npm_package_devDependencies__sushiswap_sdk: string;
		npm_package_devDependencies__sveltejs_adapter_auto: string;
		npm_package_dependencies__ledgerhq_hw_transport_webusb: string;
		VSCODE_DEBUGPY_ADAPTER_ENDPOINTS: string;
		VSCODE_INJECTION: string;
		npm_package_devDependencies__types_readable_stream: string;
		npm_package_devDependencies_autoprefixer: string;
		npm_package_devDependencies_daisyui: string;
		npm_package_devDependencies_svelte_check: string;
		npm_package_dependencies_svelte_chartjs: string;
		HOME: string;
		SHLVL: string;
		npm_package_config_YAKKL_TYPE: string;
		npm_package_scripts_build_chrome_proprv: string;
		npm_package_devDependencies__types_bn_js: string;
		npm_package_devDependencies__uniswap_v3_sdk: string;
		npm_package_devDependencies_easyqrcodejs: string;
		npm_package_devDependencies_webextension_polyfill: string;
		npm_package_type: string;
		VSCODE_GIT_ASKPASS_MAIN: string;
		npm_package_scripts_dev_v1_chrome: string;
		npm_package_scripts_test: string;
		npm_package_devDependencies_clipboard: string;
		npm_package_dependencies__ledgerhq_hw_transport_webhid: string;
		npm_package_devDependencies_lodash: string;
		npm_package_devDependencies_node_polyfill_webpack_plugin: string;
		npm_package_scripts_build_env_prod: string;
		npm_package_devDependencies__internationalized_date: string;
		npm_package_dependencies__rollup_plugin_node_resolve: string;
		LOGNAME: string;
		LESS: string;
		npm_package_scripts_build_chrome: string;
		npm_package_scripts_firefox_store_zip: string;
		npm_package_scripts_format: string;
		npm_package_devDependencies_embla_carousel_svelte: string;
		npm_package_devDependencies_ethereum_blockies_base64: string;
		npm_lifecycle_script: string;
		VSCODE_GIT_IPC_HANDLE: string;
		npm_package_devDependencies_prettier_plugin_tailwindcss: string;
		COREPACK_ENABLE_AUTO_PIN: string;
		npm_package_scripts_package: string;
		npm_package_devDependencies_vite_plugin_node_polyfills: string;
		NVM_BIN: string;
		npm_package_devDependencies__types_chrome: string;
		npm_package_devDependencies__types_mustache: string;
		npm_package_devDependencies_readable_stream: string;
		npm_package_scripts_dev2_chrome: string;
		npm_package_devDependencies__types_uuid: string;
		npm_package_devDependencies__types_zxcvbn: string;
		npm_package_devDependencies_dts_cli: string;
		npm_config_user_agent: string;
		GIT_ASKPASS: string;
		VSCODE_GIT_ASKPASS_NODE: string;
		npm_package_devDependencies__playwright_test: string;
		npm_package_devDependencies__types_node: string;
		npm_package_devDependencies_stream_browserify: string;
		npm_package_devDependencies_axios: string;
		npm_package_devDependencies_dotenv_webpack: string;
		npm_package_devDependencies_path_browserify: string;
		npm_package_devDependencies_svelte_radix: string;
		npm_package_scripts_prepare: string;
		npm_package_devDependencies__uniswap_sdk_core: string;
		CLAUDECODE: string;
		npm_package_scripts_check: string;
		npm_package_devDependencies_yup: string;
		COLORTERM: string;
		npm_package_devDependencies__uniswap_router_sdk: string;
		npm_node_execpath: string;
		NODE_ENV: string;
		[key: `PUBLIC_${string}`]: undefined;
		[key: `${string}`]: string | undefined;
	}
}

/**
 * Similar to [`$env/dynamic/private`](https://svelte.dev/docs/kit/$env-dynamic-private), but only includes variables that begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) (which defaults to `PUBLIC_`), and can therefore safely be exposed to client-side code.
 * 
 * Note that public dynamic environment variables must all be sent from the server to the client, causing larger network requests — when possible, use `$env/static/public` instead.
 * 
 * Dynamic environment variables cannot be used during prerendering.
 * 
 * ```ts
 * import { env } from '$env/dynamic/public';
 * console.log(env.PUBLIC_DEPLOYMENT_SPECIFIC_VARIABLE);
 * ```
 */
declare module '$env/dynamic/public' {
	export const env: {
		[key: `PUBLIC_${string}`]: string | undefined;
	}
}
