#!/usr/bin/env python3
import os
import sys

YAKKL_PATH = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(YAKKL_PATH)
from scripts.lib.yakkl_tools import parse_cache_script_args
from scripts.lib import clean_venv_cache, clean_node_cache, clean_emoji_cache

def main():
    # type: () -> None
    args = parse_cache_script_args("This script cleans unused yakkl caches.")
    os.chdir(YAKKL_PATH)
    clean_venv_cache.main(args)
    clean_node_cache.main(args)
    clean_emoji_cache.main(args)

if __name__ == "__main__":
    main()
