#!/usr/bin/env python3
import os
import shutil
import sys
import subprocess
import logging
import time
import configparser

TARBALL_ARCHIVE_PATH = "/home/yakkl/archives"
os.environ["PYTHONUNBUFFERED"] = "y"

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from scripts.lib.yakkl_tools import DEPLOYMENTS_DIR, FAIL, ENDC, \
    su_to_yakkl, get_deployment_lock, release_deployment_lock, assert_running_as_root, \
    get_config_file, get_deploy_options

config_file = get_config_file()  # type: configparser.RawConfigParser
deploy_options = get_deploy_options(config_file)

assert_running_as_root(strip_lib_from_paths=True)

logging.Formatter.converter = time.gmtime
logging.basicConfig(format="%(asctime)s upgrade-yakkl: %(message)s",
                    level=logging.INFO)

if len(sys.argv) != 2:
    print(FAIL + "Usage: %s <tarball>" % (sys.argv[0],) + ENDC)
    sys.exit(1)

tarball_path = sys.argv[1]

error_rerun_script = "%s/current/scripts/upgrade-yakkl %s" % (DEPLOYMENTS_DIR, tarball_path)
get_deployment_lock(error_rerun_script)

try:
    # Copy the release tarball to an archival path that's readable by
    # the Yakkl user, and then unpack it from that directory, so that
    # we can unpack using the Yakkl user even if the original path was
    # not readable by the Yakkl user.
    logging.info("Archiving the tarball under %s" % (TARBALL_ARCHIVE_PATH,))
    os.makedirs(TARBALL_ARCHIVE_PATH, exist_ok=True)
    archived_tarball_path = os.path.join(TARBALL_ARCHIVE_PATH, os.path.basename(tarball_path))
    shutil.copy(tarball_path, archived_tarball_path)
    subprocess.check_output(["chown", "-R", "yakkl:yakkl", TARBALL_ARCHIVE_PATH])

    logging.info("Unpacking the tarball")
    unpack_yakkl = os.path.realpath(os.path.join(os.path.dirname(__file__), 'unpack-yakkl'))
    deploy_path = subprocess.check_output([unpack_yakkl, archived_tarball_path],
                                          preexec_fn=su_to_yakkl, universal_newlines=True)

    # Chdir to deploy_path and then run upgrade-yakkl-stage-2 from the
    # new version of Yakkl (having the upgrade logic run from the new
    # version is much better for fixing bugs in the upgrade process).
    deploy_path = deploy_path.strip()
    os.chdir(deploy_path)
    subprocess.check_call([os.path.abspath("./scripts/lib/upgrade-yakkl-stage-2"), deploy_path]
                          + deploy_options)
finally:
    release_deployment_lock()
