[program:zmirror]
command=/home/yakkl/python-yakkl-api/yakkl/integrations/zephyr/zephyr_mirror.py --site=https://zephyr.yakkl.com --stamp-path=/home/yakkl/ --user=tabbott/extra --forward-class-messages --log-path=/home/yakkl/logs/mirror-log --on-startup-command="/home/yakkl/python-yakkl-api/yakkl/integrations/zephyr/zmirror-renew-kerberos"
priority=200                   ; the relative start priority (default 999)
autostart=true                 ; start at supervisord start (default: true)
autorestart=true               ; whether/when to restart (default: unexpected)
stopsignal=TERM                 ; signal used to kill process (default TERM)
stopwaitsecs=30                ; max num secs to wait b4 SIGKILL (default 10)
user=yakkl                    ; setuid to this UNIX account to run the program
redirect_stderr=true           ; redirect proc stderr to stdout (default false)
stdout_logfile=/var/log/yakkl/zmirror.log         ; stdout log path, NONE for none; default AUTO
environment=HOME="/home/yakkl",USER="yakkl"

[program:sync-public-streams]
command=/home/yakkl/python-yakkl-api/yakkl/integrations/zephyr/sync-public-streams --site=https://zephyr.yakkl.com
priority=200                   ; the relative start priority (default 999)
autostart=true                 ; start at supervisord start (default: true)
autorestart=true               ; whether/when to restart (default: unexpected)
stopsignal=TERM                 ; signal used to kill process (default TERM)
stopwaitsecs=30                ; max num secs to wait b4 SIGKILL (default 10)
user=yakkl                    ; setuid to this UNIX account to run the program
redirect_stderr=true           ; redirect proc stderr to stdout (default false)
stdout_logfile=/var/log/yakkl/sync-public-streams.log         ; stdout log path, NONE for none; default AUTO
environment=HOME="/home/yakkl"
