# This configuration proxies requests to /thumbor to a copy of the
# thumbor service installed locally on the Yakkl server.
location /thumbor {
    rewrite /thumbor/(.*) /$1 break;
    proxy_pass http://thumbor;
    include /etc/nginx/yakkl-include/proxy;
}
