#!/usr/bin/env python3

"""
This tool is for updating API key field `yakklrc` files of dummy users
in development environment, with the correct keys from the database.
Ensure running this outside of vagrant environment.
Usage:
./tools/update-yakklrc-api-field /path/to/yakklrc_dev
"""

import argparse
import configparser
import os
import subprocess
import sys

YAKKL_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, YAKKL_PATH)
from scripts.lib.yakkl_tools import is_vagrant_env_host

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('path', metavar='FILE', type=str, nargs='+',
                    help='config file of dummy users in development server')
args = parser.parse_args()

yakklrc_paths_list = args.path
for yakklrc_path in yakklrc_paths_list:
    yakklrc = configparser.ConfigParser()
    result = ''
    try:
        with open(yakklrc_path, 'r') as f:
            yakklrc.read_file(f, yakklrc_path)
        api_details = yakklrc['api']
        email = api_details['email']
        key = api_details['key']
        site = api_details['site']
        if 'localhost' not in site:
            result = 'ABORTED'
            reason = 'Script to be used for development server config files only'
    except (KeyError, configparser.MissingSectionHeaderError):
        result = 'FAILURE'
        reason = 'Could not parse file due to missing required fields/sections'
    except FileNotFoundError:
        result = 'ABORTED'
        reason = 'No yakklrc file found at specified path'

    if result not in ('ABORTED', 'FAILURE'):
        # Make sure the cwd is the root of Yakkl checkout.
        os.chdir(YAKKL_PATH)

        if is_vagrant_env_host(YAKKL_PATH):
            arguments = ['vagrant', 'ssh', '--command',
                         './manage.py print_initial_password ' + email]
        else:
            # Support users who don't have vagrant based setup
            arguments = ['./manage.py', 'print_initial_password', email]
        # We redirect 'stderr' to 'stdout' to avoid 'Connection to 127.0.0.1 closed'
        # appearing after this script finishes.
        output = subprocess.check_output(arguments, stderr=subprocess.STDOUT).decode('UTF-8')
        new_key = output.split()[6]

        if new_key != key:
            try:
                yakklrc.set('api', 'key', new_key)
                with open(yakklrc_path, 'w+') as w:
                    yakklrc.write(w)
                result = 'SUCCESS'
                reason = 'API field updated for user %s' % (email,)
            except (IOError, OSError):
                result = 'FAILURE'
                reason = 'Writing to file unsuccessful'
        else:
            result = 'SUCCESS'
            reason = 'API key for user %s is already consistent' % (email,)
    print('{}: {}: {}'.format(yakklrc_path, result, reason))
