CREATE USER NAGIOS;
GRANT USAGE ON SCHEMA YAKKL TO NAGIOS;
GRANT USAGE ON SCHEMA PUBLIC TO NAGIOS;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO NAGIOS;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA yakkl TO NAGIOS;
GRANT SELECT ON ALL TABLES IN SCHEMA yakkl TO NAGIOS;
ALTER DEFAULT PRIVILEGES IN SCHEMA YAKKL GRANT SELECT ON TABLES TO NAGIOS;
ALTER DEFAULT PRIVILEGES IN SCHEMA YAKKL GRANT SELECT ON SEQUENCES TO NAGIOS;
ALTER ROLE NAGIOS SET SEARCH_PATH TO PUBLIC,YAKKL;
